name: BuildingWordBattle
version: '${project.version}'
main: me.koutachan.buildingwordbattle.BuildingWordBattle
author: [KoutaChan1212, 7mi_chan]
commands:
  start:
    permission: minecraft.op
  admin:
    permission: minecraft.op
  change-mode:
    permission: minecraft.op
  reloadConfig:
    permission: minecraft.op
  forcestop:
    permission: minecraft.op