name: BuildingWordBattle
version: '${project.version}'
main: me.koutachan.buildingwordbattle.BuildingWordBattle
commands:
  debug:
    permission: minecraft.op
  start:
    permission: minecraft.op
  admin:
    permission: minecraft.op
  reloadConfig:
    permission: minecraft.op
  forcestop:
    permission: minecraft.op